apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cloud-vault-provider
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kvv2"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "demo"
          serviceAccountRef:
            name: "eso-sa"
            namespace: default
