apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cloud-vault-provider
    kind: ClusterSecretStore
  target:
    name: my-eso-secret
  data:
  - secretKey: username
    remoteRef:
      key: secret/
      property: username
  - secretKey: password
    remoteRef:
      key: secret/
      property: password
